#cirmuventing rake file not found error
language: generic

# give travis super user power
sudo: required

#Tell travis to get a copy of docker ready to go
services:
  - docker

#configurations to be done before test runs
before_install: 
  - docker build -t macshild/docker-react -f dockerfile.dev .

#commands needed to be executed to run the test suite
script:
  #tell travis to run test on docker and exit test upon completion
  - docker run -e CI=true macshild/docker-react npm run test

#instructions for deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-246056739136"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"




