# download base image
FROM node:alpine as builder

#specify directory in container
WORKDIR /app

#copy dependency file into workdir
COPY package.json .

#install dependencies into img Fs
RUN npm install

#copy all other files into workdir
COPY . .

#specify defualt command
RUN npm run build


#specify which service to be used as the server
FROM nginx

#specify which port to expose to the deployment host
EXPOSE 80

#specify which  files to be served up by nginx
COPY --from=builder /app/build /usr/share/nginx/html
